
import SocketContext from "./context/SocketContext";
import UserContext from "./context/UserContext";
import "./globals.css";
import { Inter, Geist } from 'next/font/google';
import { ToastContainer } from 'react-toastify';
import ThemeContext from "./context/ThemeContext";
import SideBar from "@/components/sideBar";
import { getUser } from "@/lib/getUser";
export const geist = Geist({
  subsets: ['latin'],       // required
  weight: ['100','200','300','400','500','600','700','800','900'],   // import only the weights you need
  display: 'swap',          // avoids invisible text
});
export const inter = Inter({
  subsets: ['latin'],       // required
  weight: ['100','200','300','400','500','600','700','800','900'],   // import only the weights you need
  display: 'swap',          // avoids invisible text
});
// export const metadata = {
//   title: "Create Next App",
//   description: "Generated by create next app",
// };

export default async function RootLayout({ children }) {
   const user = await getUser()
  return (
    <html lang="en" className="light" >
      <body
        className={` antialiased`}>
          <ThemeContext>
          <SocketContext>
        <UserContext Initialuser={user}>
         
        {children}
        <ToastContainer/>
        </UserContext>
          </SocketContext>
           </ThemeContext>
      </body>
    </html>
  );
}
