
import SocketContext from "./context/SocketContext";
import UserContext from "./context/UserContext";
import "./globals.css";
import { Montserrat } from 'next/font/google';
import { ToastContainer } from 'react-toastify';

const montserrat = Montserrat({
  subsets: ['latin'],       // required
  weight: ['100','200','300','400','500','600','700','800','900'],   // import only the weights you need
  display: 'swap',          // avoids invisible text
});
export const metadata = {
  title: "Create Next App",
  description: "Generated by create next app",
};

export default function RootLayout({ children }) {
  return (
    <html lang="en">
      <body
        className={`${montserrat.className} antialiased`}>
          <SocketContext>
        <UserContext>
        {children}
        <ToastContainer/>
        </UserContext>
          </SocketContext>
      </body>
    </html>
  );
}
