
import SocketContext from "./context/SocketContext";
import UserContext from "./context/UserContext";
import "./globals.css";
import { Inter, Montserrat } from 'next/font/google';
import { ToastContainer } from 'react-toastify';
import ThemeContext from "./context/ThemeContext";

const montserrat = Montserrat({
  subsets: ['latin'],       // required
  weight: ['100','200','300','400','500','600','700','800','900'],   // import only the weights you need
  display: 'swap',          // avoids invisible text
});
export const inter = Inter({
  subsets: ['latin'],       // required
  weight: ['100','200','300','400','500','600','700','800','900'],   // import only the weights you need
  display: 'swap',          // avoids invisible text
});
// export const metadata = {
//   title: "Create Next App",
//   description: "Generated by create next app",
// };

export default function RootLayout({ children }) {
  return (
    <html lang="en">
      <body
        className={`${montserrat.className} antialiased`}>
          <ThemeContext>
          <SocketContext>
        <UserContext>
        
          
        {children}
        <ToastContainer/>
        </UserContext>
          </SocketContext>
           </ThemeContext>
      </body>
    </html>
  );
}
